/* ==========================================================================
 * dump.cpp — the expected-values dump written beside each generated table.
 *
 * The C# port asserts against these dumps, so expected values are never
 * hand-written. Format reference: net/corpus/README.md.
 * ========================================================================== */

#include "d4all.h"

#include <stdio.h>
#include <string.h>

#include "util.h"
#include "dump.h"

/* Escape a byte string into C-ish text: printable ASCII verbatim, everything
 * else as \xHH. Keeps the dump diffable and unambiguous. */
static void dumpEscaped( FILE *fp, const char *p, unsigned long len )
{
   unsigned long k;

   fputc( '"', fp );
   for ( k = 0; k < len; k++ )
   {
      unsigned char c = (unsigned char)p[k];
      if ( c == '"' || c == '\\' )
         fprintf( fp, "\\%c", c );
      else if ( c >= 0x20 && c <= 0x7E )
         fputc( c, fp );
      else
         fprintf( fp, "\\x%02X", c );
   }
   fputc( '"', fp );
}

/* Header and field descriptors read straight from the file, not through the
 * API. This matters: d4create rewrites some creation types before storing them
 * ('X' -> 'M', 'Z' -> 'C', both with nullBinary bit 0x04, DBF-FORMAT.md §5),
 * and the API reports the creation type back. The port must match the bytes,
 * so the bytes are what the dump records. */
static int dumpRawHeaderAndDescriptors( FILE *out, const char *path )
{
   unsigned char h[32], d[32];
   unsigned headerLen;
   int nFields, i;
   FILE *fp = fopen( path, "rb" );

   if ( fp == 0 || fread( h, 1, 32, fp ) != 32 )
   {
      if ( fp ) fclose( fp );
      fprintf( stderr, "  ERROR: cannot read header of %s\n", path );
      return 1;
   }

   headerLen = (unsigned)( h[8] | ( h[9] << 8 ) );

   fprintf( out, "version      0x%02X\n", h[0] );
   fprintf( out, "lastUpdate   %02d-%02d-%02d  (yy mm dd, frozen)\n", h[1], h[2], h[3] );
   fprintf( out, "numRecs      %lu\n",
            (unsigned long)( h[4] | ( h[5] << 8 ) | ( h[6] << 16 ) | ( (unsigned long)h[7] << 24 ) ) );
   fprintf( out, "headerLen    %u\n", headerLen );
   fprintf( out, "recordLen    %u\n", (unsigned)( h[10] | ( h[11] << 8 ) ) );
   fprintf( out, "hasMdxMemo   0x%02X\n", h[28] );
   fprintf( out, "codePage     0x%02X\n", h[29] );

   /* Descriptors run from offset 32 up to the 0x0D terminator. */
   nFields = (int)( ( headerLen - 32 - 1 ) / 32 );

   fprintf( out, "\n[descriptors]   (as stored on disk)\n" );
   for ( i = 0; i < nFields; i++ )
   {
      char name[12];

      if ( fread( d, 1, 32, fp ) != 32 )
      {
         fclose( fp );
         fprintf( stderr, "  ERROR: truncated descriptor %d in %s\n", i + 1, path );
         return 1;
      }
      if ( d[0] == 0x0D )     /* terminator reached early (long-field-name form) */
         break;

      memcpy( name, d, 11 );
      name[11] = 0;

      fprintf( out, "%d %-10s type=%c offset=%lu len=%u dec=%u flags=0x%02X hasTag=%u\n",
               i + 1, name, d[11],
               (unsigned long)( d[12] | ( d[13] << 8 ) | ( d[14] << 16 ) | ( (unsigned long)d[15] << 24 ) ),
               d[16], d[17], d[18], d[31] );
   }

   fclose( fp );
   return 0;
}

static int isMemoType( int type )
{
   return type == r4memo || type == r4gen || type == r4memoBin;
}

int dumpTable( CODE4 *cb, const char *outDir, const char *fileName )
{
   char dbfPath[520], dumpPath[520];
   const char *dot;
   DATA4 *data;
   FILE *out;
   int nFields, i;

   sprintf( dbfPath, "%s\\%s", outDir, fileName );

   dot = strrchr( fileName, '.' );
   sprintf( dumpPath, "%s\\%.*s.dump.txt", outDir,
            dot ? (int)( dot - fileName ) : (int)strlen( fileName ), fileName );

   out = fopen( dumpPath, "wb" );      /* "wb": LF endings, so the dump is
                                        * identical on any host */
   if ( out == 0 )
   {
      fprintf( stderr, "  ERROR: cannot create %s\n", dumpPath );
      return 1;
   }

   fprintf( out, "# CodeBase.NET corpus dump\n" );
   fprintf( out, "# Generated by test-files-generator from the original CodeBase C library.\n" );
   fprintf( out, "# Do not edit by hand; regenerate instead.\n" );
   fprintf( out, "file         %s\n", fileName );

   if ( dumpRawHeaderAndDescriptors( out, dbfPath ) != 0 )
   {
      fclose( out );
      return 1;
   }

   data = d4open( cb, dbfPath );
   if ( data == 0 )
   {
      fclose( out );
      return fail( cb, "reopen for dump" );
   }

   nFields = d4numFields( data );

   fprintf( out, "\n[fields]        (as the C library reports them after open)\n" );
   fprintf( out, "recCount %ld numFields %d\n", (long)d4recCount( data ), nFields );
   for ( i = 1; i <= nFields; i++ )
   {
      FIELD4 *f = d4fieldJ( data, (short)i );
      fprintf( out, "%d %s type=%c len=%d dec=%d",
               i, f4name( f ), f4type( f ), (int)f4len( f ), (int)f4decimals( f ) );
      /* Emitted only when true, so tables without nullable fields keep the
       * dump they had. Note d4numFields excludes the hidden _NullFlags field
       * (d4declar.h:594), so this list is one shorter than [descriptors]. */
      if ( f4nullable( f ) )
         fprintf( out, " nullable=1" );
      fprintf( out, "\n" );
   }

   fprintf( out, "\n[records]\n" );
   for ( d4top( data ); !d4eof( data ); d4skip( data, 1 ) )
   {
      fprintf( out, "rec %ld deleted=%d\n", (long)d4recNo( data ), d4deleted( data ) ? 1 : 0 );

      for ( i = 1; i <= nFields; i++ )
      {
         FIELD4 *f    = d4fieldJ( data, (short)i );
         int     type = f4type( f );

         fprintf( out, "  %-10s ", f4name( f ) );

         if ( isMemoType( type ) )
         {
            unsigned long len = f4memoLen( f );

            /* The in-record memo reference first (4-byte binary or 10-byte
             * ASCII block id, FPT-MEMO.md §3.4), then the memo contents. */
            fprintf( out, "ref=" );
            dumpEscaped( out, f4ptr( f ), (unsigned long)f4len( f ) );
            fprintf( out, " len=%lu ", len );
            dumpEscaped( out, f4memoPtr( f ), len );
         }
         else
         {
            dumpEscaped( out, f4ptr( f ), (unsigned long)f4len( f ) );

            switch ( type )
            {
               case r4num:
               case r4float:
               case r4double:
               case r4currency:
                  fprintf( out, " dbl=%.17g", f4double( f ) );
                  break;
               case r4int:
                  fprintf( out, " long=%ld", (long)f4long( f ) );
                  break;
               case r4date:
                  fprintf( out, " str=[%s]", f4str( f ) );
                  break;
               case r4dateTime:
                  /* f4str does not decode datetimes; f4dateTime does
                   * (F4FIELD.C:1940). Blank datetimes come back empty. */
                  fprintf( out, " str=[%s]", f4dateTime( f ) );
                  break;
               default:
                  break;
            }
         }

         if ( f4null( f ) )
            fprintf( out, " null=1" );

         fprintf( out, "\n" );
      }

      /* The _NullFlags bitmap itself, raw. It is not part of the field list
       * above (d4numFields hides it), so without this the port's null decoding
       * would only be gated through the null=1 flags and never against the
       * stored bytes. Absent — hence invisible in the other dumps — when the
       * table has no nullable fields. */
      if ( d4fieldNull( data ) != 0 )
      {
         FIELD4 *nf = d4fieldNull( data );

         fprintf( out, "  %-10s ", f4name( nf ) );
         dumpEscaped( out, f4ptr( nf ), (unsigned long)f4len( nf ) );
         fprintf( out, "\n" );
      }
   }

   d4close( data );
   fclose( out );
   printf( "  dump -> %.*s.dump.txt\n",
           dot ? (int)( dot - fileName ) : (int)strlen( fileName ), fileName );
   return 0;
}
